---
kind: pipeline
type: docker
name: default

steps:
  - name: Checks
    image: nixos/nix:master
    commands:
      - nix --extra-experimental-features "nix-command flakes" flake check
      - nix --extra-experimental-features "nix-command flakes" build .#checks.x86_64-linux.ansi-to-tui-llvm-coverage
  - name: upload-codecov
    image: robertstettner/drone-codecov
    files: result
